### ISSUE TITLE
Refactor minitwit_tests.py 

### ISSUE THREAD

**Issue by Kether180** [Group-O-Minitwit/minitwit-group-o#5]

**Comment by ChristofferTofteng** [comment]
We have some questions about how to properly use the db fixture and how to get the data from the db that needs to be asserted

**Comment by Kether180** [comment]
@ChristofferTofteng  Me and @HrisyToteva  were wondering about it too . We will meet with @AbsoluteZer01  on Monday , maybe he knows.
