### ISSUE TITLE
Refactor minitwit.py3

### ISSUE THREAD

**Issue by Kether180** [Group-O-Minitwit/minitwit-group-o#6]

**Comment by MikkelNilsson** [comment]
The endpoints for the simulator is as follows:
- [ ] GET /latest
- [ ] POST /register
- [ ] GET /msgs
- [ ] GET /msgs/<username>
- [ ] POST /msgs/<username>
- [ ] GET /fllws/<username>
- [ ] POST/fllws/<username>
